#ifndef PORTEXCEPTION_H
#define PORTEXCEPTION_H

#define portRV_INSTRUCTION_ADDRESS_MISALIGNED 0x0
#define portRV_INSTRUCTION_ACCESS_FAULT 0x1
#define portRV_ILLEGAL_INSTRUCTION 0x2
#define portRV_LOAD_ADDRESS_MISALIGNED 0x4
#define portRV_LOAD_ACCESS_FAULT 0x5
#define portRV_STORE_ADDRESS_MISALIGNED 0x6
#define portRV_STORE_ACCESS_FAULT 0x7
#define portRV_INSTRUCTION_PAGE_FAULT 0x12
#define portRV_LOAD_PAGE_FAULT 0x13
#define portRV_STORE_PAGE_FAULT 0x15

#endif // PORTEXCEPTION_H
