FREEDOM_SDK_PATH := FreeRTOS/Demo/RISC-V-Qemu-sifive_e-FreedomStudio/freedom-e-sdk
FREEDOM_SDK_DIR := $(FREERTOS_DIR)/$(FREEDOM_SDK_PATH)

FREEDOM_WRAP_DIR := $(FREEDOM_SDK_DIR)/libwrap
FREEDOM_ENV_DIR  := $(FREEDOM_SDK_DIR)/env
FREEDOM_E300_DIR := $(FREEDOM_ENV_DIR)/freedom-e300-hifive1/

FREEDOM_SDK_DRV_DIR := $(FREEDOM_SDK_DIR)/drivers/
FREEDOM_SDK_PLIC_DIR := $(FREEDOM_SDK_DRV_DIR)/plic/

FREEDOM_SDK_INCLUDES := \
	-I $(FREEDOM_SDK_DIR)/include \
	-I $(FREEDOM_ENV_DIR) \
	-I $(FREEDOM_E300_DIR) \
	-I $(FREEDOM_SDK_DRV_DIR)

FREEDOM_SDK_SOURCE := \
	$(FREEDOM_SDK_PLIC_DIR)/plic_driver.c \
	$(FREEDOM_E300_DIR)/init.c \
	$(FREEDOM_WRAP_DIR)/sys/write.c \
	$(FREEDOM_WRAP_DIR)/sys/isatty.c

FREEDOM_SDK_ASM := \
	$(FREEDOM_ENV_DIR)/start.S \
	$(FREEDOM_ENV_DIR)/entry.S

FREEDOM_SDK_BUILD_DIR := $(BUILD_DIR)/SDK
FREEDOM_SDK_OBJS := $(patsubst %.c,$(FREEDOM_SDK_BUILD_DIR)/%.o,$(notdir $(FREEDOM_SDK_SOURCE)))
FREEDOM_SDK_OBJS += $(patsubst %.S,$(FREEDOM_SDK_BUILD_DIR)/%.o,$(notdir $(FREEDOM_SDK_ASM)))

VPATH += \
	$(FREEDOM_ENV_DIR) \
	$(FREEDOM_WRAP_DIR)/sys/ \
	$(FREEDOM_E300_DIR) \
	$(FREEDOM_SDK_PLIC_DIR)

FREEDOM_SDK_CFLAGS := -include sys/cdefs.h

LDFLAGS += -Wl,--wrap=write -Wl,--wrap=isatty
